# Generated by Django 4.1.7 on 2023-04-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID_user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Mail', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=50)),
                ('FullName', models.CharField(max_length=100)),
                ('GivenName', models.CharField(max_length=100)),
                ('Birthday', models.DateField(max_length=20)),
                ('Acc_Type', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Jobtitle', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Avatar', models.CharField(max_length=50)),
                ('User_Status', models.BooleanField(max_length=20)),
            ],
        ),
    ]
