# Generated by Django 4.1.7 on 2023-04-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='GivenName',
            new_name='displayName',
        ),
    ]
