# Generated by Django 4.1.7 on 2023-04-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_rename_givenname_users_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
