# Generated by Django 4.1.7 on 2023-04-06 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Phone',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
