# Generated by Django 4.1.7 on 2023-04-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Avatar',
            field=models.CharField(max_length=1000),
        ),
    ]
