# Generated by Django 4.1.7 on 2023-03-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUKRS', models.CharField(max_length=10)),
                ('BUTXT', models.CharField(max_length=100)),
                ('ORT01', models.CharField(max_length=1000)),
                ('LAND1', models.CharField(max_length=10)),
                ('DESC', models.CharField(max_length=50)),
            ],
        ),
    ]
